config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'

  root 'welcome#index'
  get '/profile'=> 'welcome#profile', as: :profile
  get '/profile/:id' => 'users#profile'
  post '/frozen' => 'welcome#frozen'
  get '/unfrozen' => 'welcome#unfrozen'
  get '/qiniu_token' => 'welcome#qiniu_token'

  resources :deposits, only: [:index, :create]
  resources :delivers do
    get 'apply', on: :collection
  end
  resources :wangwangs, only: [:index, :create, :destroy]
  resources :shops, only: [:index, :create, :destroy]
  resources :tasks do
    collection do
      get 'my_task'
      get 'my_order'
    end

    member do
      patch 'validate'
      get 'reject'
      get 'confirm'
    end

  end

  resources :templates, only: [:index, :destroy, :create]
  resources :orders, only: [:index] do
    get 'reject', on: :member
    get 'confirm', on: :member
  end
  resources :blacklists

  resource :authenticates, only:[:edit, :update]
  resources :pages, only: [:index, :show]
  resource :bills, only: [:show]
  resource :extracts, :vips
  resource :referrals, only: [:show]
  resources :invitations, only: [:index]
  resources :task_autos do
    get 'start', on: :member
    get 'stop', on: :member
  end
  resources :complaints

  namespace :admin do
    root 'welcome#index'
    get '/profile/:id' => 'users#profile'
    resources :deposits, only: [:index, :create]
    resources :delivers, only: [:index] do
      get 'reject', on: :member
      get 'confirm', on: :member
    end

    resources :wangwangs, only: [:index] do
      get 'reject', on: :member
      get 'confirm', on: :member
    end

    resources :shops, only: [:index] do
      get 'reject', on: :member
      get 'confirm', on: :member
    end
    resources :users do
      get 'reject', on: :member
      get 'confirm', on: :member
      get 'official', on: :member
      get 'cancel_official', on: :member
      get 'lock', on: :member
      get 'unlock', on: :member
    end

    resources :pages
    resources :extracts
    resources :complaints do
        get 'finished', on: :member
    end

    authenticate :admin do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  devise_for :users, path: '',controllers: {
    registrations: 'users/registrations'
  }
  devise_for :admins, path: 'admin'

  mount ChinaCity::Engine => '/china_city'

end

app/views/admin/pages/_form.html.slim
= render partial: 'shared/error', locals: {title: '页面发布失败', error: @page}
= form_for [:admin, @page], html:{class: 'ui form'} do |f|

  .fields
    .field.four.wide
      = f.label :name
      = f.text_field :name
    .field.four.wide
      = f.label :code
      = f.text_field :code
    .field.four.wide
      = f.label :category_id
      = f.select :category_id,
          options_from_collection_for_select(@categories, :id, :name, @page.category_id),
          {include_blank: true},{class: 'ui dropdown'}
  .field
    = f.label :content
    = f.text_area :content, id: 'content_edit'

  = f.submit '确定', class: 'ui button positive'
- content_for :css do
  = stylesheet_link_tag 'simditor'
- content_for :js do
  = javascript_include_tag 'simditor'
  javascript:
    $(function(){
      var editor = new Simditor({
        textarea: $('#content_edit'),
        toolbarFloat: true,
        defaultImage: "#{image_path 'jenny.jpg'}"
      });
    })

app/views/admin/pages/edit.html.slim
= render 'admin/pages/form'

app/views/admin/pages/index.html.slim
= link_to '添加页面', new_admin_page_path, class: 'ui button positive'
table.ui.table
  thead
    tr
      th #
      th 名称
      th 编码
      th 分类
      th 创建时间
      th 操作

  tbody
    - @pages.each do |page|
      tr
        td = page.id
        td = page.name
        td = page.code
        td = page.category.nil? ? '' : page.category.name
        td = page.created_at.to_minute
        td
          = link_to '编辑', edit_admin_page_path(page), class: 'ui button positive'
          = link_to '删除', admin_page_path(page), method: 'delete',
                      data: {confirm: '确定删除'}, class: 'ui button negative'

app/views/admin/pages/new.html.slim
= render 'admin/pages/form'