config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'

  root 'welcome#index'
  get '/profile'=> 'welcome#profile', as: :profile
  get '/profile/:id' => 'users#profile'
  post '/frozen' => 'welcome#frozen'
  get '/unfrozen' => 'welcome#unfrozen'
  get '/qiniu_token' => 'welcome#qiniu_token'

  resources :deposits, only: [:index, :create]
  resources :delivers do
    get 'apply', on: :collection
  end
  resources :wangwangs, only: [:index, :create, :destroy]
  resources :shops, only: [:index, :create, :destroy]
  resources :tasks do
    collection do
      get 'my_task'
      get 'my_order'
    end

    member do
      patch 'validate'
      get 'reject'
      get 'confirm'
    end

  end

  resources :templates, only: [:index, :destroy, :create]
  resources :orders, only: [:index] do
    get 'reject', on: :member
    get 'confirm', on: :member
  end
  resources :blacklists

  resource :authenticates, only:[:edit, :update]
  resources :pages, only: [:index, :show]
  resource :bills, only: [:show]
  resource :extracts, :vips
  resource :referrals, only: [:show]
  resources :invitations, only: [:index]
  resources :task_autos do
    get 'start', on: :member
    get 'stop', on: :member
  end
  resources :complaints

  namespace :admin do
    root 'welcome#index'
    get '/profile/:id' => 'users#profile'
    resources :deposits, only: [:index, :create]
    resources :delivers, only: [:index] do
      get 'reject', on: :member
      get 'confirm', on: :member
    end

    resources :wangwangs, only: [:index] do
      get 'reject', on: :member
      get 'confirm', on: :member
    end

    resources :shops, only: [:index] do
      get 'reject', on: :member
      get 'confirm', on: :member
    end
    resources :users do
      get 'reject', on: :member
      get 'confirm', on: :member
      get 'official', on: :member
      get 'cancel_official', on: :member
      get 'lock', on: :member
      get 'unlock', on: :member
    end

    resources :pages
    resources :extracts
    resources :complaints do
        get 'finished', on: :member
    end

    authenticate :admin do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  devise_for :users, path: '',controllers: {
    registrations: 'users/registrations'
  }
  devise_for :admins, path: 'admin'

  mount ChinaCity::Engine => '/china_city'

end

app/models/vip.rb
# == Schema Information
#
# Table name: vips
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  pricing    :integer
#  largess    :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_vips_on_user_id  (user_id)
#

class Vip < ActiveRecord::Base
  extend Enumerize
  belongs_to :user

  enumerize :pricing, in: {
    :ten_day => 10,
    :one_month => 30, :three_month => 90,
    :six_month => 180,:tlewve_month => 360
  }

  validate :with_amount_limit, unless: Proc.new{|vip| vip.largess}

  after_create :update_vip_at
  after_create :with_largess, :with_bill, unless: Proc.new{|vip| vip.largess}

  private
    # 更新vip到期时间
    def update_vip_at
      if self.user.vip_at.blank? || self.user.vip_at< Time.now
        self.user.vip_at = self.pricing.value.days.from_now
      else
        self.user.vip_at += self.pricing.value.days
      end
      self.user.save
    end

    # 优惠赠送
    def with_largess
      case self.pricing
        when 'three_month'
          Vip.create(user: self.user, pricing: 'ten_day', largess: true)
        when 'six_month'
          Vip.create(user: self.user, pricing: 'one_month', largess: true)
        when 'tlewve_month'
          Vip.create(user: self.user, pricing: 'three_month', largess: true)
      end
    end

    # 交易明细
    def with_bill
      self.user.decrement(:amount, self.pricing.value)
      self.user.save
      Bill.create(
        user: self.user,
        log: self.id,
        amount: -self.pricing.value,
        state: 'vip',
      )
    end

    # 检查余额
    def with_amount_limit
      errors.add(:base, "账户余额为: #{sprintf('%0.02f元', self.user.amount)}, 不能购买此套餐。") if self.user.amount < self.pricing.value
    end
end

app/controllers/vips_controller.rb
class VipsController < ApplicationController

  def show
    @vip = Vip.new
  end

  def create
    @vip = current_user.vips.build(pricing: params[:pricing])
    if @vip.save
      flash[:success] = 'VIP套餐购买成功'
      redirect_to :back
    else
      render :show
    end
  end
end

app/views/vips/show.html.slim
.ui.segment
  .ui.grid.centered.three.column
    .column
      .ui.list
        .item
          .header  商家
        .item 1. 自己动放单功能
        .item 2. 任务始终排在任务大厅前面
        .item 3. 提现48小时处理
    .column
      .ui.list
        .item
          .header  刷手
        .item 1.自动接任务功能
        .item 2.提现48小时处理
= render partial: 'shared/error', locals: {title: '购买套餐失败', error: @vip}
.ui.grid.four.column.equal.height.pricing
  .stretched.row
    .column
      .ui.segment.center.aligned
        h3.ui.header.block 体验版
        p 时间: 30天
        p 价格: ￥30
        p 赠送: 暂无
        .ui.divider
        = button_to '立即购买', vips_path(pricing: 'one_month'),
            class: 'ui button green', data:{confirm: '确定购买体验版'}

    .column
      .ui.segment.center.aligned
        .highlighted
        h3.ui.header.block 基础版
        p 时间: 60天
        p 价格: ￥60
        p 赠送: 10天
        .ui.divider
        = button_to '立即购买', vips_path(pricing: 'three_month'),
            class: 'ui button green', data:{confirm: '确定购买基础版'}
    .column
      .ui.segment.center.aligned
        h3.ui.header.block 专业版
        p 时间: 180天
        p 价格: ￥180
        p 赠送: 30天
        .ui.divider
        = button_to '立即购买', vips_path(pricing: 'six_month'),
            class: 'ui button green', data:{confirm: '确定购买专业版'}
    .column
      .ui.segment.center.aligned
        h3.ui.header.block 至尊版
        p 时间: 360天
        p 价格: ￥360
        p 赠送: 90天
        .ui.divider
        = button_to '立即购买', vips_path(pricing: 'tlewve_month'),
            class: 'ui button green', data:{confirm: '确定购买至尊版'}