config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'

  root 'welcome#index'
  get '/profile'=> 'welcome#profile', as: :profile
  get '/profile/:id' => 'users#profile'
  post '/frozen' => 'welcome#frozen'
  get '/unfrozen' => 'welcome#unfrozen'
  get '/qiniu_token' => 'welcome#qiniu_token'

  resources :deposits, only: [:index, :create]
  resources :delivers do
    get 'apply', on: :collection
  end
  resources :wangwangs, only: [:index, :create, :destroy]
  resources :shops, only: [:index, :create, :destroy]
  resources :tasks do
    collection do
      get 'my_task'
      get 'my_order'
    end

    member do
      patch 'validate'
      get 'reject'
      get 'confirm'
    end

  end

  resources :templates, only: [:index, :destroy, :create]
  resources :orders, only: [:index] do
    get 'reject', on: :member
    get 'confirm', on: :member
  end
  resources :blacklists

  resource :authenticates, only:[:edit, :update]
  resources :pages, only: [:index, :show]
  resource :bills, only: [:show]
  resource :extracts, :vips
  resource :referrals, only: [:show]
  resources :invitations, only: [:index]
  resources :task_autos do
    get 'start', on: :member
    get 'stop', on: :member
  end
  resources :complaints

  namespace :admin do
    root 'welcome#index'
    get '/profile/:id' => 'users#profile'
    resources :deposits, only: [:index, :create]
    resources :delivers, only: [:index] do
      get 'reject', on: :member
      get 'confirm', on: :member
    end

    resources :wangwangs, only: [:index] do
      get 'reject', on: :member
      get 'confirm', on: :member
    end

    resources :shops, only: [:index] do
      get 'reject', on: :member
      get 'confirm', on: :member
    end
    resources :users do
      get 'reject', on: :member
      get 'confirm', on: :member
      get 'official', on: :member
      get 'cancel_official', on: :member
      get 'lock', on: :member
      get 'unlock', on: :member
    end

    resources :pages
    resources :extracts
    resources :complaints do
        get 'finished', on: :member
    end

    authenticate :admin do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  devise_for :users, path: '',controllers: {
    registrations: 'users/registrations'
  }
  devise_for :admins, path: 'admin'

  mount ChinaCity::Engine => '/china_city'

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id               :integer          not null, primary key
#  shop_id          :integer
#  link             :string
#  keywords         :string
#  price            :decimal(10, 2)
#  duration         :string(10)
#  level            :string(10)
#  chat             :string(10)
#  desc             :string
#  spec             :string
#  receive_time     :boolean
#  comment_time     :boolean
#  comment          :string
#  extra            :string(10)
#  state            :string(10)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  commission       :decimal(10, 2)
#  commission_extra :decimal(10, 2)
#  task_type        :string(10)
#  cover            :string
#  producer_id      :integer
#  consumer_id      :integer
#  wangwang_id      :integer
#  ip               :string(20)
#  code             :string(20)
#
# Indexes
#
#  index_tasks_on_code         (code)
#  index_tasks_on_consumer_id  (consumer_id)
#  index_tasks_on_duration     (duration)
#  index_tasks_on_extra        (extra)
#  index_tasks_on_ip           (ip)
#  index_tasks_on_level        (level)
#  index_tasks_on_producer_id  (producer_id)
#  index_tasks_on_shop_id      (shop_id)
#  index_tasks_on_state        (state)
#  index_tasks_on_task_type    (task_type)
#  index_tasks_on_wangwang_id  (wangwang_id)
#

class Task < ActiveRecord::Base
  extend Enumerize
  include AASM


  def to_id
    "#{code}"
  end

  default_scope { order 'updated_at DESC'}

  # 商家
  belongs_to :producer, class_name: 'User'
  # 刷手
  belongs_to :consumer, class_name: 'User'
  # 店铺
  belongs_to :shop
  # 旺旺
  belongs_to :wangwang

  def cover_url
    self.cover.blank? ? 'helen.jpg' : ENV['QINIU_BUCKET_DOMAIN']+self.cover+'-task'
  end

  def commission_for_consumer
    self.commission * 0.9
  end

  enumerize :duration, in: [
    :six, :ten, :fifteen, :twenty, :twentyfive,
    :thirty, :forty
  ], default: :six

  enumerize :level, in: [
    :normal, :one, :two,:three, :four, :five, :max
  ], default: :normal

  enumerize :chat, in: [
    :normal, :simple, :complex
  ], default: :normal

  enumerize :task_type, in: [
    :pc, :phone
  ], default: :pc



  aasm column: :state do
    state :pending, initial: true
    state :talking
    state :confirmed
    state :applying
    state :finished

    event :talk do
      transitions from: :pending, to: :talking
    end
    event :reject do
      transitions from: [:confirmed, :talking], to: :pending
    end
    event :confirm do
      transitions from: :talking, to: :confirmed
    end

    event :apply  do
     transitions from: :confirmed, to: :applying
    end

    event :finish  do
      after do
        self.consumer.with_lock do
          self.consumer.increment(:amount, self.commission_for_consumer)
          self.consumer.save
        end

        Bill.create(
          user: self.consumer,
          log: self.to_id,
          amount: self.commission_for_consumer,
          state: 'finish_task',
        )
      end
     transitions from: :applying, to: :finished
    end

  end

  validates_presence_of :shop_id, :link, :keywords,
                        :price, :duration, :level,
                        :chat, :task_type, :desc, :cover
  validates :link, format: {with: /id=\d+/}, allow_blank: true
  validates :price, :commission_extra, numericality:true, allow_blank: true
  validates :extra, numericality:{ only_integer: true}, allow_blank: true
  validates :spec, length:{ maximum: 15 }, allow_blank: true

  validate :commission_within_limit, on: :create

  # 发布任务扣除佣金
  after_create do |task|

    task.producer.with_lock do
      task.producer.decrement(:amount, task.commission)
      task.producer.save
    end
    Bill.create(
      user: task.producer,
      log: task.to_id,
      amount: -task.commission,
      state: 'publish_task',
    )
  end

  # 取消任务返还资金
  before_destroy do |task|

    task.producer.with_lock do
      task.producer.increment(:amount, task.commission)
      task.producer.save
    end
    Bill.create(
      user: task.producer,
      log: task.to_id,
      amount: task.commission,
      state: 'cancel_task',
    )
  end

  before_create do |task|
    task.code = rand(1000000..9999999)
  end

  # 任务完成支付佣金给刷手
  def self.finish_task
    applying.where('updated_at < ?', 5.minutes.ago).each do |task|
      TaskWorker.perform_async(task.id)
    end
  end
  validate :ip_count_within_limit, :shop_wangwang_within_limit, :blacklist_within_limit,
            on: :update, if: Proc.new{|task|
              task.state == 'pending' && task.ip && task.consumer_id && task.wangwang_id }

  private

  # 黑名单限制
  def blacklist_within_limit
    #  我屏蔽了你
    black_from_producer = Blacklist.where('user_id = ? AND target_id = ?', self.producer, self.consumer).any?
    #  你屏蔽了我
    black_from_consumer = Blacklist.where('user_id = ? AND target_id = ?', self.consumer, self.producer).any?

    if black_from_producer || black_from_consumer
      errors.add(:base, "你们之间进入了黑名单，不能接手任务")
    end
  end

    def ip_count_within_limit
      count = Task.where(consumer: self.consumer).where(ip: self.ip).where('created_at > ?', 1.days.ago).size
      errors.add(:base, "同一个IP地址24小时内最多接3个任务，请重启路由或更换IP地址") if count >=3
    end

    def shop_wangwang_within_limit
      count = Task.where(wangwang: self.wangwang)
                   .where(shop: self.shop)
                   .where('created_at >= ?', 30.days.ago).size

      errors.add(:base, "您所选择的旺旺在30天已经接手过该店铺的任务，请使用其他旺旺!") if count >=1
    end
    # 计算佣金总额
    def commission_within_limit
      # 基础价格
      self.commission = 3
      # 时长增加
      case self.duration
      when 'ten'
        self.commission += 1
      when 'fifteen'
        self.commission += 2
      when 'twenty'
        self.commission += 3
      when 'twentyfive'
        self.commission += 4
      when 'thirty'
        self.commission += 5
      when 'forty'
        self.commission += 6
      end
      # 假聊
      case self.chat
      when 'simple'
        self.commission += 0.5
      when 'complex'
        self.commission += 1
      end

      # 手机单
      self.commission += 1 if self.task_type == 'phone'

      # 增拍
      self.commission += self.extra.to_i.abs

      # 追加佣金
      self.commission += self.commission_extra.to_i.abs
      if self.producer
        errors.add(:base, '余额不足') if self.commission > self.producer.amount
      end
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :producer, only: [:new, :create]
  before_action :consumer, only: [:edit, :update]

  def index
    @tasks = Task.pending.includes(:shop)
  end

  def new
    # 数据自动填充: 来自模版->上次成功纪录->新内容
    if params[:template]
      @task = Task.new(JSON.parse(current_user.templates.find(params[:template]).content))
    elsif cookies[:task_param]
      @task = Task.new(JSON.parse(cookies[:task_param]))
    else
      @task = Task.new(
        receive_time: true,
        comment_time: true,
        desc: "手动输入关键词搜索进店浏览3分钟拍下宝贝，上中下评价销量全屏截图"
        )
    end
  end


  def create
    @task = current_user.tasks.build(task_param)
    if @task.save
      flash[:success] = "任务发布成功"
      cookies[:task_param] = JSON.generate(task_param)
      redirect_to new_task_path
    else
      render :new
    end
  end

  def show
    @task = Task.find(params[:id])
    render :new
  end

  def validate
    @task = Task.find(params[:id])
    if @task.link.match(/id=\d+/).to_a[0] == params[:link].match(/id=\d+/).to_a[0]
      @task.apply!
      flash[:success] = '宝贝地址验证成功'
    else
      flash[:error] = '宝贝地址验证失败'
    end
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.pending.find(params[:id])
    redirect_to_condition = true
    case
      when @task.price < 100
        redirect_to_condition = false
      when current_user.frozen_amount >=100 && @task.price <= 300
        redirect_to_condition = false
      when current_user.frozen_amount >= 300 && @task.price <= 500
        redirect_to_condition = false
      when current_user.frozen_amount >=500 && @task.price <= 800
        redirect_to_condition = false
      when current_user.frozen_amount >= 1000 && @task.price > 800
        redirect_to_condition = false
    end

    if redirect_to_condition
      flash[:error] = '目前冻结的资金不能接手改任务'
      redirect_to deposits_path
      return
    end

  end

  def update

    @task = Task.pending.find(params[:id])
    if task_consumer_param[:wangwang_id].blank?
      flash[:error] = '请选择接手任务的旺旺'
      redirect_to :back
      return
    end
    @task.consumer = current_user
    @task.ip = request.remote_ip

    if @task.update(task_consumer_param)
      @task.talk!
      redirect_to my_order_tasks_path
    else
      render :edit
    end
  end

  def my_task
    @pending_count = current_user.tasks.pending.count
    @talking_count = current_user.tasks.talking.count
    @confirmed_count = current_user.tasks.confirmed.count
    @applying_count = current_user.tasks.applying.count
    @finished_count = current_user.tasks.finished.count
    @all_count = current_user.tasks.count

    if %w(pending talking confirmed applying finished).include?( params[:type] )
      @tasks = current_user.tasks.send(params[:type].to_sym)
    else
      @tasks = current_user.tasks
    end
  end

  def my_order
    @talking_count = current_user.orders.talking.count
    @confirmed_count = current_user.orders.confirmed.count
    @applying_count = current_user.orders.applying.count
    @finished_count = current_user.orders.finished.count
    @all_count = current_user.orders.count

    if %w(pending talking confirmed applying finished).include?( params[:type] )
      @tasks = current_user.orders.send(params[:type].to_sym)
    else
      @tasks = current_user.orders
    end
  end


  def reject
    @task = current_user.tasks.find(params[:id])
    @task.ip = nil
    @task.wangwang_id = nil
    @task.consumer= nil
    @task.reject
    if @task.save

      flash[:success] = '审核操作成功: 拒绝'
      redirect_to my_task_tasks_path
    end
  end

  def confirm
    @task = current_user.tasks.find(params[:id])
    if @task.confirm!
      flash[:success] = '审核操作成功: 通过'
      redirect_to my_task_tasks_path
    end
  end

  def destroy
    current_user.tasks.find(params[:id]).destroy
    flash[:success] = '任务取消成功'
    redirect_to my_task_tasks_path
  end


  private
    def task_param
      params.require(:task).permit!
    end

    def task_consumer_param
      params.require(:task).permit(:wangwang_id)
    end

    # 商家验证
    def producer
      # 页面数据
      @auto = TaskAuto.new
      @templates = current_user.templates
      @auto_templates = current_user.templates.auto_template

      # 数据验证
      @shops = current_user.shops.confirmed
      if @shops.blank?
        flash[:error] = '发布任务前需要绑定店铺掌柜'
        redirect_to shops_path
        return
      end


      unless ['checked', 'officialed'].include?(current_user.state)
        flash[:error] = '发布任务前需要进行账户认证'
        redirect_to edit_authenticates_path
        return
      end
    end

    # 刷手验证
    def consumer
      @wangwangs = current_user.wangwangs.available
      if current_user.delivers.confirmed.size<=0
        flash[:error] = '接手任务需要有可以使用的收获地址'
        redirect_to delivers_path
        return
      end
      if @wangwangs.blank?
        flash[:error] = '接手任务前需要绑定旺旺'
        redirect_to wangwangs_path
        return
      end

      unless ['checked', 'officialed'].include?(current_user.state)
        flash[:error] = '接手任务前需要进行账户认证'
        redirect_to edit_authenticates_path
        return
      end
    end

end

app/helpers/tasks_helper.rb
module TasksHelper
  def task_level(task)
    case task.level
      when 'max'
        content_tag(:i, '', class: 'icon diamond blue')

      when 'one'
        content_tag(:i, '', class: 'icon heart red')

      when 'two'
        content_tag(:i, '', class: 'icon heart red')+
        content_tag(:i, '', class: 'icon heart red')

      when 'three'
        content_tag(:i, '', class: 'icon heart red')+
        content_tag(:i, '', class: 'icon heart red')+
        content_tag(:i, '', class: 'icon heart red')
      when 'four'
        content_tag(:i, '', class: 'icon heart red')+
        content_tag(:i, '', class: 'icon heart red')+
        content_tag(:i, '', class: 'icon heart red')+
        content_tag(:i, '', class: 'icon heart red')
      when 'five'
        content_tag(:i, '', class: 'icon heart red')+
        content_tag(:i, '', class: 'icon heart red')+
        content_tag(:i, '', class: 'icon heart red')+
        content_tag(:i, '', class: 'icon heart red')+
        content_tag(:i, '', class: 'icon heart red')
      end
  end

  def task_type(task)
    if task.task_type == 'phone'
      content_tag(:i, '', class: 'icon tablet red')
    end
  end
end

app/views/tasks/_nav.html.slim
.ui.menu.item.six
  = link_to "全部( #{@all_count} )",
          my_task_tasks_path, class: 'item'
  = link_to "等待接手( #{@pending_count} )",
          my_task_tasks_path(type: 'pending'), class: 'item'
  = link_to "等待审核( #{@talking_count} )",
          my_task_tasks_path(type: 'talking'), class: 'item'
  = link_to "进行中( #{@confirmed_count} )",
          my_task_tasks_path(type: 'confirmed'), class: 'item'
  = link_to "已完成( #{@applying_count} )",
          my_task_tasks_path(type: 'applying'), class: 'item'
  = link_to "已付款( #{@finished_count} )",
          my_task_tasks_path(type: 'finished'), class: 'item'

app/views/tasks/_nav_order.html.slim
.ui.menu.item.five
  = link_to "全部( #{@all_count} )",
          my_order_tasks_path, class: 'item'
  = link_to "等待审核( #{@talking_count} )",
          my_order_tasks_path(type: 'talking'), class: 'item'
  = link_to "审核通过( #{@confirmed_count} )",
          my_order_tasks_path(type: 'confirmed'), class: 'item'
  = link_to "宝贝已验证( #{@applying_count} )",
          my_order_tasks_path(type: 'applying'), class: 'item'
  = link_to "已收佣金( #{@finished_count} )",
          my_order_tasks_path(type: 'finished'), class: 'item'

app/views/tasks/_validate.html.slim
- unless @task.new_record?
  - if @task.state == 'confirmed' && current_user == @task.consumer
      = form_for @task, url: validate_task_path(@task), html:{class: 'ui form'} do |f|
        .field
          .ui.input.action.left.labeled.big
            .ui.label 宝贝地址
            = text_field_tag :link

            button class="ui button positive" 验证

app/views/tasks/edit.html.slim
= render partial: 'shared/error', locals: {title: '接单失败', error: @task}
h2 任务

table.ui.table
  thead
    tr
      th 任务ID和时间
      th 发布人
      th 佣金
      th 价格
      th 特殊需求
      th 旺旺



  tbody
      tr
        td
          = @task.to_id
          = task_type(@task)
          p.description
            i.icon.calendar
            = @task.created_at.to_minute
        td = @task.producer.name
        td
          span.commission = sprintf("%0.02f",@task.commission_for_consumer)
          | 元
        td = sprintf("%0.02f元",@task.price)
        td.description
          p = task_level(@task)
          p
            span.ui.label.tiny ="时长: #{@task.duration_text}"
            - unless @task.extra.blank?
              span.ui.label.tiny = "增拍: #{@task.extra}个"
          - unless @task.spec.blank?
            p
              span.ui.label.tiny = @task.spec
        td.six.wide
          =  form_for [@task], html:{class: 'ui form'} do |f|
            .field
              = f.select :wangwang_id,
                  options_from_collection_for_select(@wangwangs, :id, :account),
                  {include_blank: true},{class: 'ui dropdown'}

            = f.submit '确定', class: 'ui button tiny positive'
            = link_to '取消', tasks_path, class: 'ui tiny button'

app/views/tasks/index.html.slim
h2 任务大厅

table.ui.table
  thead
    tr
      th 任务ID和时间
      th 发布人
      th 佣金
      th 价格
      th 时长
      th 特殊需求
      th 操作

  tbody
    - @tasks.each do |task|
        tr
          td

            = task.to_id
            = task_type(task)
            p.description
              i.icon.calendar
              = task.created_at.to_minute
          td = task.shop.user.name
          td
            span.commission = sprintf("%0.02f",task.commission_for_consumer)
            | 元
          td = sprintf("%0.02f元",task.price)
          td = task.duration_text


          td
            = task_level(task)
            p
              - unless task.extra.blank?
                span.ui.label.tiny = "增拍#{task.extra}个"
              - unless task.spec.blank?
                span.ui.label.tiny = task.spec
          td
            = link_to '接单', edit_task_path(task), class: 'ui button tiny green'

app/views/tasks/my_order.html.slim
= render 'tasks/nav_order'

- case params[:type]
- when 'talking'
  h2 等待审核的任务
- when 'confirmed'
  h2 审核通过的任务
- when 'applying'
  h2 宝贝已验证的任务
- when 'finished'
  h2 已收佣金的任务
- else
  h2 已接到的任务

table.ui.table
  thead
    tr
      th 任务ID和时间
      th 发布人
      th 佣金
      th 价格
      th 特殊需求
      th 状态
      th 操作

  tbody
  - @tasks.each do |task|
      tr
        td
          = task.to_id
          = task_type(task)
          p.description
            i.icon.calendar
            = task.created_at.to_minute
        td
          = task.producer.name
          = link_to "tencent://Message/?Uin=#{task.producer.qq}" do
            i.icon.qq.circular.green

        td
          span.commission = sprintf("%0.02f",task.commission_for_consumer)
          | 元
        td = sprintf("%0.02f元",task.price)

        td.description
          p = task_level(task)
          p
            span.ui.label.tiny ="时长: #{task.duration_text}"
            - unless task.extra.blank?
              span.ui.label.tiny = "增拍: #{task.extra}个"
          - unless task.spec.blank?
            p
              span.ui.label.tiny = task.spec
        td
           span.ui.label.green
            =task.aasm.human_state
        td

          - case task.state
            - when 'confirmed'
              = link_to '详情', task_path(task), class: 'ui button mini positive'
          - if task.consumer
            = link_to '申诉', new_complaint_path(task: task.code), class: 'ui button mini negative'

app/views/tasks/my_task.html.slim
= render 'tasks/nav'

- case params[:type]
- when 'pending'
  h2 等待接手的任务
- when 'talking'
  h2 等待审核的任务
- when 'confirmed'
  h2 进行中的任务
- when 'applying'
  h2 已完成的任务
- else
  h2 我发布的任务


.ui.red.buttons
  = link_to '发布任务', new_task_path, class: 'ui button'
  -if current_user.templates.any?
    .ui.floating.dropdown.icon.button
      i.dropdown.icon
      .menu
        - current_user.templates.each do |template|
          = link_to template.name, new_task_path(template: template.id), class: 'item'

table.ui.table
  thead
    tr
      th 任务ID和时间
      th 接手人
      th 价格和佣金
      th 特殊需求
      th 操作


  tbody
  - @tasks.each do |task|
      tr
        td
          = task.to_id
          = task_type(task)
          p.description
            i.icon.calendar
            = task.created_at.to_minute
        td
          - if task.state != 'pending'
            = link_to task.consumer.name, '#', class: 'order_user', 'data-id': task.id
            = link_to "tencent://Message/?Uin=#{task.consumer.qq}" do
              i.icon.qq.circular.green

        td
          p
            | 佣金:
            span.commission = sprintf("%0.02f",task.commission)
            | 元

          p = sprintf("价格: %0.02f元",task.price)


        td.description
          p = task_level(task)
          p
            span.ui.label.tiny ="时长: #{task.duration_text}"
            - unless task.extra.blank?
              span.ui.label.tiny = "增拍: #{task.extra}个"
          - unless task.spec.blank?
            p
              span.ui.label.tiny = task.spec
        td

          - if task.state != 'pending'
            p = task.wangwang.account
          p

            = link_to '详情', task_path(task), class: 'ui button mini positive'
            - if task.state == 'confirmed' && Time.now - task.updated_at > 30.minutes
              = link_to '更换刷手', reject_task_path(task), class: 'ui button mini negative'
            - case task.state
              - when 'pending'
                = link_to '取消', task_path(task), method: 'delete', class: 'ui button mini positive'
              - when 'talking'
                = link_to '同意', confirm_task_path(task), class: 'ui button mini positive'
                = link_to '拒绝', reject_task_path(task), class: 'ui button mini negative'
            - if task.consumer
              = link_to '申诉', new_complaint_path(task: task.code), class: 'ui button mini negative'


.ui.modal.profile
  i.close.icon
  .header 接单人信息
  .content 加载中...
  .actions
    .ui.button.positive 关闭


- content_for(:js) do
  javascript:
    $(function(){
      $('a.order_user').click(function(){
        $.get('/profile/'+$(this).data('id'), function(data){
          content = "<div class='ui grid two column'>"
          content += "<div class='column'>";
          content += "<p>姓名: "+data.name+"</p>";
          content += "<p>旺旺: "+data.wangwang+"</p>";
          content += "<p>已完成任务数: "+data.order_count+"</p>";
          content += "<h4>收获地址</h4>"
          content += "<p>收件人: "+data.deliver_name+"</p>"
          content += "<p>地址: "+data.deliver_address+"</p>"
          content += "</div>";

          content += "<div class='column'>";
          content += "<p>支付宝名称: "+data.alipay_name+"</p>";
          content += "<p>支付宝账号: "+data.alipay_account+"</p>";
          content += "</div>";
          content += '</div>'
          $('.ui.modal.profile .content').html(content);
        });
        $('.ui.modal.profile').modal('show');
      })
    })